service: xingzo-api-test # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: users/create
          method: get
